### PR TITLE
Initial work to get mocha tests in place for React code

### PR DESCRIPTION
**Pull request by kristoferpelchat**
This PR is primarily around mocha setup as the upgrade took some time. There were some babel configuration changes that needed to happen as you will see in this PR. The plan is to get tests in place for React code so I can play with it a bit before I write the React Native writer. 

I have added a `test/data` folder that contains sample input data, which is the main reason for the high file count in this PR. 

I did NOT break any existing functionality with the Webpack build for npm registry distribution. I did update babel to 7 so I could use the newer way to tell mocha about babel when running tests.

### CODE REVIEW

**Review by fetmar — APPROVED** [review]
Looks good but one question. Do you plan to have this be merged back into the original repo? Because if you do, it's probably best to stick with their coding style and not use our standardjs linting/formatting.

**Comment by fetmar** [comment]
Oh, and why is this in your account? :)

**Comment by kristoferpelchat** [comment]
> Looks good but one question. Do you plan to have this be merged back into the original repo? Because if you do, it's probably best to stick with their coding style and not use our standardjs linting/formatting.

I am not sure if this will ever go back in as they developer of Appfairy seems to be MIA. You make a VERY good point...but I feel like we can cross that bridge later if we need to.

**Comment by kristoferpelchat** [comment]
> Oh, and why is this in your account? :)

We will eventually be open source...and I am pushing to open source buoyant wallet. More to come on that. :)

**Pull request merged**
